# Generated by Django 4.1.3 on 2022-11-28 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('ID_product', models.BigIntegerField(default=0)),
                ('Score', models.FloatField(default=1)),
                ('Price', models.FloatField(default=0.0)),
                ('Image', models.URLField()),
                ('Track', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=60)),
                ('num_of_searchs', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=60)),
                ('dateInput', models.DateTimeField(default=datetime.datetime(2022, 11, 27, 21, 57, 8, 914960))),
            ],
        ),
    ]
