# Generated by Django 4.1.3 on 2022-11-28 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBgestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='num_of_searchs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='search',
            name='dateInput',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 21, 59, 59, 961828)),
        ),
    ]
