# Generated by Django 4.1.3 on 2022-11-28 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBgestor', '0002_search_num_of_searchs_alter_search_dateinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='dateInput',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 3, 55, 40, 457139)),
        ),
        migrations.AlterField(
            model_name='search',
            name='num_of_searchs',
            field=models.IntegerField(default=0),
        ),
    ]
