# Generated by Django 4.1.3 on 2022-11-28 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBgestor', '0003_alter_search_dateinput_alter_search_num_of_searchs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_of_searchs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='dateInput',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 13, 57, 38, 366114)),
        ),
    ]
